### PR TITLE
Make defaultBody configurable

### PR DESCRIPTION
**Pull request by SiarheiVolkau**
Default message with badge and sound its not always suitable and we need a way to configure it.
This patch provides a way to configure `defaultBody` of message via application config.

### CODE REVIEW

**Comment by fa2mm** [comment]
Ok, but you can make:
$alert = ['badge' => +1, 'sound' => 'default'] +1, 'sound' => 'default'];
$body['aps'] = array_merge($defaultBody, $alert);

**Comment by fa2mm** [comment]
Done! But you can just set $alert = ['badge' => +1, 'sound' => 'newSound'] and rewrite $body['aps']

array_merge(oldArray, newArray) - newArray rewrite oldArray

**Comment by SiarheiVolkau** [comment]
Usually i made silent pushes, badge and sound not needed at all.
Editing code of external component is a bad idea since changes not reflect in project history and can be lost when site are moved to another hosting.

With this change i can configure component as:
'apns' => [
			'class' => 'tecsvit\apns\src\Sender',
			**'defaultBody' => [],**
		],
and that's all.

**Comment by SiarheiVolkau** [comment]
Thank you very much.

**Comment by fa2mm** [comment]
Yes, I agree with your arguments. Welcome

**Pull request merged**
